name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Триггер для запуска при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      run: docker build -t my-flask-app .
    
    - name: Run tests
      run: docker run my-flask-app pytest
    
    - name: Scan for vulnerabilities
      run: docker run my-flask-app safety check --ignore 70612
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Push to Docker Hub
      run: |
        docker tag my-flask-app ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ github.sha }}
    
    - name: Deploy to production
      if: success()  # Выполнять деплой только если предыдущие шаги успешно завершились
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ github.sha }}
        docker stop my-flask-app || true
        docker rm my-flask-app || true
        docker run -d -p 80:80 --name my-flask-app ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ github.sha }}

    env:
      FLASK_ENV: production
